import dns from 'node:dns';
dns.setServers(['8.8.8.8', '8.8.4.4'])
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="bg-slate-50 text-slate-900 dark:bg-zinc-950 dark:text-zinc-50 min-h-screen transition-colors duration-200">
        <ThemeProvider attribute="class" defaultTheme="light">
          <Navbar />
          <main className="min-h-[calc(100vh-150px)]">
            {children}
          </main>
          <Footer />
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{
              style: {
                background: '#fff',
                color: '#1e293b',
                border: '1px solid #fce7f3',
                borderRadius: '12px',
                fontSize: '14px',
                fontWeight: '500',
                padding: '12px 24px',
                boxShadow: '0 4px 12px rgba(219, 39, 119, 0.08)',
              },
              success: {
                iconTheme: {
                  primary: '#db2777',
                  secondary: '#fff',
                },
                style: {
                  border: '1px solid #fbcfe8',
                }
              },
              error: {
                iconTheme: {
                  primary: '#e11d48',
                  secondary: '#fff',
                },
                style: {
                  border: '1px solid #fecdd3',
                }
              },
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}